name: Deploy MCW Apps to Azure (Development)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Applications
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: |
          cd packages/database
          npx prisma generate

      - name: Build applications
        run: npx turbo build --filter=front-office... --filter=back-office...

      - name: Prepare front-office deployment
        run: |
          cd apps/front-office
          npm install --save-dev fs-extra
          node deploy.js

      - name: Prepare back-office deployment
        run: |
          cd apps/back-office
          npm install --save-dev fs-extra
          node deploy.js

      - name: Upload front-office build
        uses: actions/upload-artifact@v3
        with:
          name: front-office-build
          path: apps/front-office/deploy

      - name: Upload back-office build
        uses: actions/upload-artifact@v3
        with:
          name: back-office-build
          path: apps/back-office/deploy

  deploy-front-office:
    name: Deploy Front Office
    needs: build
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download front-office build
        uses: actions/download-artifact@v3
        with:
          name: front-office-build
          path: ./front-office-deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "front-office-mcw-dev"
          slot-name: "Production"
          package: "./front-office-deploy"
          startup-command: "npm start"

  deploy-back-office:
    name: Deploy Back Office
    needs: build
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download back-office build
        uses: actions/download-artifact@v3
        with:
          name: back-office-build
          path: ./back-office-deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "back-office-mcw-dev"
          slot-name: "Production"
          package: "./back-office-deploy"
          startup-command: "npm start"
