name: Deploy MCW Apps to Azure (Development)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Applications
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: |
          cd packages/database
          npx prisma generate

      # Front Office App
      - name: Build front-office
        run: npx turbo build --filter=front-office...

      - name: Prepare front-office deployment
        run: |
          cd apps/front-office
          npm install --save-dev fs-extra
          node deploy.js

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy front-office to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "front-office-mcw-dev"
          slot-name: "Production"
          package: "./apps/front-office/deploy"
          startup-command: "npm start"

      # Back Office App
      - name: Build back-office
        run: npx turbo build --filter=back-office...

      - name: Prepare back-office deployment (with migrations)
        run: |
          cd apps/back-office
          npm install --save-dev fs-extra
          node deploy.js

      - name: Deploy back-office to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "back-office-mcw-dev"
          slot-name: "Production"
          package: "./apps/back-office/deploy"
          startup-command: "npm start"
