name: Deploy to Azure (Development)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: |
          cd packages/database
          npx prisma generate

      # Build all applications
      - name: Build applications
        run: npx turbo build --filter=front-office... --filter=back-office...

      # Prepare apps for deployment
      - name: Run deployment scripts
        run: |
          node apps/front-office/deploy.js
          node apps/back-office/deploy.js

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy applications
      - name: Deploy front-office
        uses: azure/webapps-deploy@v3
        with:
          app-name: "front-office-mcw-dev"
          package: "./apps/front-office"
          startup-command: "npx next start -p 8080"

      - name: Deploy back-office
        uses: azure/webapps-deploy@v3
        with:
          app-name: "back-office-mcw-dev"
          package: "./apps/back-office"
          startup-command: "node startup.js"
